# Main Application Configuration
app:
  name: "Interview Coach System"
  version: "1.0.0"
  environment: "development"
  debug: true

# Logging Configuration
logging:
  level: "ERROR"
  file: "logs/interview_coach.log"
  format: "%(asctime)s - %(name)s - %(levelname)s - [%(correlation_id)s] - %(message)s"
  max_size_mb: 100
  backup_count: 5


# Storage Configuration
storage:
  base_path: "data"
  backup_enabled: true
  max_backup_count: 10
  cleanup_interval_hours: 24

# LLM Configuration
llm:
  routing_strategy: "performance_based"
  health_check_interval: 300  # 5 minutes
  circuit_breaker:
    failure_threshold: 5
    timeout: 200
    half_open_timeout: 100
  fallback_order: ["deepseek", "qwen"]



# Performance Monitoring
performance:
  metrics_enabled: true
  collection_interval: 60  # 1 minute
  retention_period: 86400  # 24 hours

# Security Configuration
security:
  secret_key: "${SECURITY_SECRET_KEY}"
  rate_limiting:
    enabled: true
    max_requests_per_minute: 100
    burst_limit: 20

# Session Management
session:
  max_duration_hours: 4
  auto_save_interval: 300  # 5 minutes
  cleanup_old_sessions: true
  max_sessions_per_user: 10
